version: '3.8'

services:
  shortener-api:
    image: registry.mele.lat/shortener-api:latest
    container_name: shortener-api
    ports:
      - "${APP_PORT}:80"
    depends_on:
      - mongodb
      - memcached
    networks:
      - external
      - internal
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    env_file:
      - .env

  mongodb:
    image: docker.io/library/mongo:6.0
    container_name: mongodb-prod
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    networks:
      - internal
    restart: unless-stopped

  memcached:
    image: docker.io/library/memcached:1.6-alpine
    container_name: memcached-prod
    command: memcached -m 256
    networks:
      - internal
    restart: unless-stopped

networks:
  external:
    driver: bridge
  internal:
    driver: bridge
    internal: true
    attachable: false

volumes:
  mongodb_data:
