services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: shortener-api-fpm
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ../:/var/www/
  nginx:
    image: nginx:latest
    container_name: shortener-api-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../public:/var/www/html/public